### ISSUE TITLE
wsi_deploy_models  not found

### ISSUE THREAD

**Issue by jackhanyuan** [hwanglab/TILs_Analysis#1]
I'm trying detect tils regions, and your work is nice, but repo https://github.com/hwanglab/wsi_deploy_models is not found, can you reopen it?  Thank you so much!

**Comment by Dkaaaaa** [comment]
> I'm trying detect tils regions, and your work is nice, but repo https://github.com/hwanglab/wsi_deploy_models is not found, can you reopen it? Thank you so much!

Hi, did u have the model file? Can u share it for me?

Thanks a lot!
